export const labels: Partial<Record<string, string>> = {
    name: "Nome",
    email: "Email",
    phone: "Telemóvel",
    document: "Documento",
    birthday: "Data de Nascimento",
    whereFoundUs: "Onde nos encontrou?",
    healthQ1: 'Indique se há diagnóstico positivo para Hepatite B e C, HIV/AIDS, sífilis, tuberculose, herpes, eczema, psoríase, acne, rosácea, diabetes, distúrbios de coagulação sanguínea, problemas cardíacos, doenças autoimunes, câncer, epilepsia, gravidez, queloide, anemia, hemofilia ou doença autoimune, vitiligo.',
    healthQ2: 'Você já teve alguma reação alérgica a pigmentos de tatuagem ou outras tintas?',
    healthQ3: 'Você está tomando algum medicamento que possa afetar a cicatrização?',
    healthQ4: 'Você está sob tratamento médico atual ou possui alguma condição de saúde que deva ser informada?',
    beforeProcedureRQ1: 'Afirmo ter conferido todos os detalhes da tatuagem (posição, grafia, datas, desenho, etc). Estou ciente de que a tatuagem é um processo artístico.',
    beforeProcedureRQ2: 'Não fiz uso de nenhum anestésico e estou ciente que caso seja descoberto o uso durante o procedimento, o mesmo será interrompido sem devolução do valor pago.',
    beforeProcedureRQ3: 'Confirmo ter mais de 18 Anos.',
    beforeProcedureRQ4: 'Afirmo ter ciência de há câmeras no ambiente laboral e autorizo a gravação de minha imagem.',
    art: 'Desenho',
    bodyPart: 'Parte do corpo',
    price: 'Preço',
    afterProcedureRQ1: 'Comprometo-me a seguir as instruções repassadas pelo profissional, a fim de que a cicatrização seja a melhor possível, estando ciente de que cada pessoa possui um tempo específico e próprio de reação.',
    afterProcedureRQ2: 'Estou ciente de que qualquer problema com a minha tatuagem deve ser tratado diretamente com o tatuador.',
    afterProcedureRQ3: 'Autorizo a veiculação do trabalho executado através meio de comunicação isentando-o de qualquer bônus e/ou ônus advindo da exposição da imagem e qualquer processo decorrente.',
    artistSignature: 'Assinatura do artista',
    clientSignature: 'Assinatura do cliente',
};