CREATE TABLE IF NOT EXISTS "tattoo" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"document" text NOT NULL,
	"birthday" date NOT NULL,
	"whereFoundUs" text,
	"healthRQ1" text NOT NULL,
	"healthQ1" text,
	"healthRQ2" text NOT NULL,
	"healthQ2" text,
	"healthRQ3" text NOT NULL,
	"healthQ3" text,
	"healthRQ4" text NOT NULL,
	"healthQ4" text,
	"beforeProcedureRQ1" text NOT NULL,
	"beforeProcedureRQ2" text NOT NULL,
	"beforeProcedureRQ3" text NOT NULL,
	"beforeProcedureRQ4" text NOT NULL,
	"art" text NOT NULL,
	"price" text NOT NULL,
	"bodyPart" text NOT NULL,
	"afterProcedureRQ1" boolean NOT NULL,
	"afterProcedureRQ2" boolean NOT NULL,
	"afterProcedureRQ3" boolean,
	"artistSignature" text NOT NULL,
	"clientSignature" text NOT NULL,
	"message2Days" text,
	"message2Weeks" text,
	"message2Months" text,
	"notes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
